language: php
php:
  - 7.3
  - 7.4
  - nightly

sudo: false

cache:
  directories:
   - vendor

install:
- travis_retry composer install --no-interaction --prefer-source

script:
- ./vendor/bin/phpunit --coverage-clover tests/logs/clover.xml
 
after_script:
  - travis_retry php vendor/bin/php-coveralls -v
